### ISSUE TITLE
Movie Release Dates iCal

### ISSUE THREAD

**Issue by TomCummings07** [TomCummings07/ARWIN#26]
ARWIN will constantly look at all blockbuster moves coming out soon and find the release date. He will then add it to an iCal file and host it on the web server. This will be picked up by calendar apps and be displayed in them.

**Comment by TomCummings07** [comment]
**Roadmap:**

- [ ] Have the Main Server search for new movies and their release dates.
- [ ] Add this data to the Database Server in ics format.
- [ ] The Web Server Hosts this data.
