### ISSUE TITLE
ARWIN-Surveillance-Camera Support

### ISSUE THREAD

**Issue by TomCummings07** [TomCummings07/ARWIN#27]
Support for the [ARWIN-Surveillance-Camera](https://github.com/TomCummings07/ARWIN-Surveillance-Camera).

**Roadmap:**

- [ ] Receive POST requests with camera data on Web Server.
- [ ] Send these data to the Main Server for processing.
- [ ] Main Server compiles frames using the metadata along with them.
- [ ] If any are missing, the Main Server sends a request to the Web Server which sends a request to the specific camera requesting a data resend.

**Data will be sent in JSON format with the following syntax:**

```
{
    "frame": "The data of the frame in bytes",
    "metadata": {
        "timecode": "The timecode of the frame in H:M:S:f",
        "device": "The device/camera ID"
    }
}
```
