### ISSUE TITLE
Cloud Storage Service

### ISSUE THREAD

**Issue by TomCummings07** [TomCummings07/ARWIN#29]
**The Idea**
A client accessible storage system hosted on the File Server and served through the Web Server.

**Roadmap:**

- [ ] Configure File Server:
     - [ ] Configure directory tree.
     - [ ] Configure signal receiver.
     - [ ] Configure request to Main Server.
     - [ ] Other necessary configurations.
- [ ] Configure Web Server:
     - [ ] Configure web route.
     - [ ] Configure request to Main Server.
     - [ ] Other necessary configurations.
- [ ] Configure Main Server:
     - [ ] Configure sending & receiving requests.

**Request Flow:**

1. The Client uploads a file.
2. Web Server obtains this file and converts it into bytes.
3. This is sent in a HTTP request to the Main Server.
4. The Main Server then redirects the file to the File Server.
5. The File Server saves the file in its Storage.
6. It then sends a success message to the Main Server which sends it to the Web Server.
7. It is then displayed to the client.
8. Similar process for a file request from the client.

**Note:** All files sent (except from the Client to the Web Server, as they use HTTPS with an SSL key) are encrypted as they are sent over HTTP which is **not** secure.
